### ISSUE TITLE
Screen tearing issue

### ISSUE THREAD

**Issue by trulysinclair** [mikepruett3/youtube-desktop#1]
Not sure if there's anything that can really be done about this, but for some reason the app has screen tearing issues which are only isolated to the app. When viewing the same video and timestamp in a regular browser there isn't an issue. Otherwise, thank you for creating this I always have youtube off to a side monitor while working on my own Electron app, and I get tired of picking between browser windows with YouTube taking one of its own. Major QoL with this app!

**Comment by mikepruett3** [comment]
I would test running with "Hardware Acceleration" disabled. If you are running on Windows, look for the "YouTube Desktop" tray icon, and right-click. Hope this helps!

**Comment by trulysinclair** [comment]
I've been running it for a few days with it off but still the same unfortunately. Nothing major, just subtle tearing here and there

**Comment by mikepruett3** [comment]
Which OS are you using?

**Comment by trulysinclair** [comment]
Windows 11. I've also had a weird but repeated issue with turning my volume down to zero and when I bring it back up, potentially too fast but my speakers boom at peak volume and only the YouTube app does this every time. Just weird haha

**Comment by trulysinclair** [comment]
I've double-checked by pulling up YouTube in Firefox, and Edge but not Chrome. It could easily be an underlying Chromium issue with Electron but I'm unsure

**Comment by mikepruett3** [comment]
Sorry, I do not use Windows anymore... as support for Windows 10 ends in a year. When I was using Windows 10, I did not have any issues with screen tearing... only remember seeing weird artifacts when the GPU or System memory usage was high. Maybe someone else who is still using Windows could try and replicate

**Comment by trulysinclair** [comment]
I understand, thank you

**Comment by mikepruett3** [comment]
Please try the latest release. I did a massive upgrade of the Electron version, and maybe that will help!
