### ISSUE TITLE
Adblocker

### ISSUE THREAD

**Issue by Zan1456** [mikepruett3/youtube-desktop#2]
Can you make a built in ublock origin extension?

**Comment by ujjwalr03** [comment]
please with custom plugins like in  
https://github.com/th-ch/youtube-music

**Comment by mikepruett3** [comment]
Ok, I have added [Ghostery's Adblocker](https://github.com/ghostery/adblocker) package into the mix. Please try now, as it seems to be working for me when I sign out of my account (I have YT Premium, so I normally do not get Ads in the first place)

**Comment by Zan1456** [comment]
It looks good to me too, thank you.
